version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPMAccessToken" > .npmrc
      - npm ci
  build:
    commands:
      - npm test
